module.exports = {
	atl: "Atlanta Hawks",
	bos: "Boston Celtics",
	cha: "Charlotte Bobcats",
	chi: "Chicago Bulls",
	cle: "Cleveland Cavaliers",
	dal: "Dallas Mavericks",
	den: "Denver Nuggets",
	det: "Detroit Pistons",
	gsw: "Golden State Warriors",
	hou: "Houston Rockets",
	ind: "Indiana Pacers",
	lac: "Los Angeles Clippers",
	lal: "Los Angeles Lakers",
	mem: "Memphis Grizzlies",
	mia: "Miami Heat",
	mil: "Milwaukee Bucks",
	min: "Minnesota Timberwolves",
	bkn: "Brookln Nets",
	noh: "New Orleans Hornets",
	nyk: "New York Knicks",
	okc: "Oklahoma City Thunder",
	orl: "Orlando Magic",
	phi: "Philadelphia 76ers",
	phx: "Phoenix Suns",
	por: "Portland Trailblazers",
	sas: "San Antonio Spurs",
	sac: "Sacramento Kings",
	tor: "Toronto Raptors",
	uth: "Utah Jazz",
	wsh: "Washington Wizards",
};
